### ISSUE TITLE
Short.io API not showing in n8n credentials list after install

### ISSUE THREAD

**Issue by tonyb250** [liamdmcgarrigle/n8n-nodes-shortio#1]
I'm self-hosting n8n and installed n8n-nodes-shortio via the GUI which shows it as installed but when trying to add the credentials for Short.io API it is not listed, does this mean it will have to be manually installed as instructed here https://docs.n8n.io/integrations/community-nodes/installation/manual-install/

Sorry if sounding dumb but have only just started using n8n and yours seemed ideal for url shortening.
Thanks.

**Comment by liamdmcgarrigle** [comment]
Hi @tonyb250 

Installing through the GUI should work

When you go in to add new credential, if you search short it should be the only option that comes up
<img width="459" alt="Screenshot 2024-06-19 at 6 27 47 AM" src="https://github.com/liamdmcgarrigle/n8n-nodes-shortio/assets/126508198/01d23f4e-5471-48eb-9555-4a2a0e0fb318">

If you don't see it there try adding the credential right from the node
<img width="459" alt="Screenshot 2024-06-19 at 6 27 47 AM" src="https://github.com/liamdmcgarrigle/n8n-nodes-shortio/assets/126508198/6cee7885-09ec-4e35-9d1a-eade70d08896">

If that doesn't work try restarting your instance, update if you have an update, and finally uninstall the custom node and then reinstall and restart your instance again if needed

Let me know if it's still not working after that.
It is working for me on 1.44.1 with n8n-nodes-shortio v0.1.1

**Comment by tonyb250** [comment]
Thanks for the reply, tried your suggestions but still not showing up.
Currently running Version 1.45.1 & v0.1.1 installed (which shows up as installed) but is still not listed in the credentials list.

**Comment by liamdmcgarrigle** [comment]
@tonyb250 do you mind taking a screen recording to show me and I'll do some testing later today based on that?

**Comment by tonyb250** [comment]
I can do that no problem, 

It has shown up if I do a search for the node but it will not allow any credentials to be added.

![Screenshot 2024-06-19 121233](https://github.com/liamdmcgarrigle/n8n-nodes-shortio/assets/69595023/20c4b70a-6889-4ef1-a1b7-8d8d8281f323)
![Screenshot 2024-06-19 121310](https://github.com/liamdmcgarrigle/n8n-nodes-shortio/assets/69595023/6c0174ed-382e-4f2c-ac1b-13c3ceeeff63)
![Screenshot 2024-06-19 121328](https://github.com/liamdmcgarrigle/n8n-nodes-shortio/assets/69595023/9a2ca7f4-1550-4bea-a8fb-b31781eceefa)
![Screenshot 2024-06-19 121351](https://github.com/liamdmcgarrigle/n8n-nodes-shortio/assets/69595023/e94032c5-71a9-4745-9f93-1abf1500f0df)
![Screenshot 2024-06-19 121407](https://github.com/liamdmcgarrigle/n8n-nodes-shortio/assets/69595023/652f7d62-d7ad-420e-81c4-30368aa7f306)

Thanks again

**Comment by tonyb250** [comment]
Hi,
I just wanted to let you know that it is now working, not sure what happened as I haven't touched anything since yesterday but I went to some other credentials and it popped up in the list.

Not sure if you did anything on your end.

The node works great once I figured out how to use it correctly. lol

Thanks again for putting this together.

**Comment by liamdmcgarrigle** [comment]
@tonyb250 Great to hear. I have not had a chance to look into it yet so it wasn't anything by me. Glad it's working!
Hopefully was just a fluke
